### ISSUE TITLE
Lack of Updates

### ISSUE THREAD

**Issue by qmaz246** [NakamaNetwork/nakama.network#84]
Hey @RoboCafaz,

I'm not sure if you're active on Discord anymore, but we've reached a full cycle of OPTC content without any stage or unit updates. Are you still interested in keeping the website running? What does it take to maintain and update the stages/units on the website? Is there a way to pass on the website to active users? Many people still use the website. Reach out in the Discord if you can.

Thanks,

Qmaz246

**Comment by RoboCafaz** [comment]
Thanks for the ping. I've posted an update on Discord which can be found [here](https://discord.com/channels/403928189111500811/403928189115695109/1116165789779771473). ([Invite link](https://discord.gg/ExppYCQ2))

tl;dr I've been out of the OPTC game for a long time and the age of [the old site's code](https://github.com/NakamaNetwork/nakama.legacy) and technology makes it hard for me to find the time to keep it maintained. I made this repo to eventually rebuild it on a more modern and maintainable platform (hopefully with automated updates) but that's... also work!
